_wandb:
    value:
        cli_version: 0.23.1
        e:
            ztes74eankt7e0225wd52x0v2gvol7ej:
                codePath: train_sdf.py
                codePathLocal: train_sdf.py
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "3605336621056"
                        used: "2803172782080"
                email: helloqxwang@gmail.com
                executable: /home/qianxu/miniconda3/envs/repr/bin/python
                git:
                    commit: 031ad14a0c1811080c249383035784dbfe7a919a
                    remote: git@github.com:helloqxwang/crossembodimentaction.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-1c9fdbdf-497a-1cc4-079b-5e1704558488
                host: qianxu-Dell-Pro-Max-Tower-T2-FCT2250
                memory:
                    total: "134489894912"
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.35
                program: /home/qianxu/Project/crossembodimentaction/train_sdf.py
                python: CPython 3.10.19
                root: /home/qianxu/Project/crossembodimentaction
                startedAt: "2026-01-06T23:32:19.649157Z"
                writerId: ztes74eankt7e0225wd52x0v2gvol7ej
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 50
            "2":
                - 1
                - 50
            "3":
                - 13
                - 16
            "4": 3.10.19
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
data:
    value: '{''data_source'': ''./data/'', ''indices'': {''start'': 0, ''end'': 100}, ''val_indices'': {''start'': 100, ''end'': 110}, ''num_instances'': 100, ''subsample'': 16384, ''batch_size'': 32, ''val_batch_size'': 32, ''max_num_links'': 5, ''load_ram'': False, ''shuffle'': True, ''num_workers'': 8, ''drop_last'': True}'
models:
    value: '{''joint_encoder'': {''input_dim'': 9, ''output_dim'': 128, ''hidden_dims'': [128, 128], ''activation'': ''gelu'', ''dropout'': 0.0, ''use_layer_norm'': False}, ''link_encoder'': {''input_dim'': 257, ''output_dim'': 128, ''hidden_dims'': [256, 256], ''activation'': ''gelu'', ''dropout'': 0.0, ''use_layer_norm'': False}, ''joint_value_encoder'': {''embed_dim'': 128, ''use_positional'': True, ''mlp_hidden'': [128], ''activation'': ''gelu'', ''dropout'': 0.0, ''use_layer_norm'': False}, ''transformer'': {''input_dim'': 128, ''model_dim'': 128, ''output_dim'': 128, ''num_heads'': 4, ''num_layers'': 4, ''mlp_ratio'': 4.0, ''dropout'': 0.1, ''attn_dropout'': 0.0, ''activation'': ''gelu'', ''use_positional_encoding'': True, ''max_length'': 32, ''norm_first'': True, ''final_layer_norm'': True}, ''decoder'': {''latent_size'': 128, ''dims'': [512, 512, 512, 512, 512, 512, 512, 512], ''dropout'': [0, 1, 2, 3, 4, 5, 6, 7], ''dropout_prob'': 0.2, ''norm_layers'': [0, 1, 2, 3, 4, 5, 6, 7], ''latent_in'': [4], ''xyz_in_all'': False, ''use_tanh'': False, ''latent_dropout'': False, ''weight_norm'': True}}'
training:
    value: '{''device'': ''cuda'', ''dtype'': ''float32'', ''debug_batch'': True, ''lr'': 0.0001, ''num_epochs'': 1, ''wandb'': {''enabled'': True, ''project'': ''action_repr'', ''run_name'': ''sdf-transformer''}}'
