test_instance_name: &name config_CLS_100

defaults:
  - conf_fk@_global_: *name
  - _self_

data:
  data_source: ./data/
  val_indices:
    start: 1
    end: 2
  num_instances: 64
  val_batch_size: 16
  num_workers: 0
  drop_last: false
  fix_q_samples: true

validation:
  device: cuda
  checkpoint_dir: ./checkpoints/mfk_CLS_100_ori
  checkpoint_epoch: 200
  save_mesh_dir: ./outputs/val_meshes
  max_mesh_per_batch: 2
  mesh:
    N: 256
    max_batch: 262144
    offset: null
    scale: null
  visualize:
    enable: True
    port: 8080
    gt_mesh_template: null  # e.g. "${data.data_source}/chain_samples/chain_{class_idx}_{instance_idx}/mesh.ply"
    show_pred_only: false
